// Copyright (c) 1998, 2006, Oracle. All rights reserved.  
package oracle.toplink.remote.corba.sun;


/**
* INTERNAL:
* oracle/toplink/remote/corba/sun/_CORBARemoteSessionControllerStub.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaRemoteSessionControllerSun.idl
* Monday, November 19, 2001 1:51:44 o'clock PM EST
*/
public class _CORBARemoteSessionControllerStub extends org.omg.CORBA.portable.ObjectImpl implements oracle.toplink.remote.corba.sun.CORBARemoteSessionController {
    // Constructors
    // NOTE:  If the default constructor is used, the
    //        object is useless until _set_delegate (...)
    //        is called.
    public _CORBARemoteSessionControllerStub() {
        super();
    }

    public _CORBARemoteSessionControllerStub(org.omg.CORBA.portable.Delegate delegate) {
        super();
        _set_delegate(delegate);
    }

    public oracle.toplink.internal.remote.Transporter getLogin() {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("getLogin", true);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return getLogin();
        } finally {
            _releaseReply(_in);
        }
    }
    // getLogin

    public oracle.toplink.internal.remote.Transporter getDefaultReadOnlyClasses() {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("getDefaultReadOnlyClasses", true);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return getDefaultReadOnlyClasses();
        } finally {
            _releaseReply(_in);
        }
    }
    // getDefaultReadOnlyClasses

    public oracle.toplink.internal.remote.Transporter scrollableCursorCurrentIndex(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("scrollableCursorCurrentIndex", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return scrollableCursorCurrentIndex(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // scrollableCursorCurrentIndex

    public oracle.toplink.internal.remote.Transporter commitRootUnitOfWork(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("commitRootUnitOfWork", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return commitRootUnitOfWork(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // commitRootUnitOfWork

    public oracle.toplink.internal.remote.Transporter scrollableCursorAbsolute(oracle.toplink.internal.remote.Transporter arg0, int arg1) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("scrollableCursorAbsolute", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _out.write_long(arg1);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return scrollableCursorAbsolute(arg0, arg1);
        } finally {
            _releaseReply(_in);
        }
    }
    // scrollableCursorAbsolute

    public oracle.toplink.internal.remote.Transporter cursoredStreamNextPage(oracle.toplink.internal.remote.Transporter arg0, int arg1) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("cursoredStreamNextPage", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _out.write_long(arg1);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return cursoredStreamNextPage(arg0, arg1);
        } finally {
            _releaseReply(_in);
        }
    }
    // cursoredStreamNextPage

    public oracle.toplink.internal.remote.Transporter executeQuery(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("executeQuery", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return executeQuery(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // executeQuery

    public oracle.toplink.internal.remote.Transporter scrollableCursorFirst(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("scrollableCursorFirst", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return scrollableCursorFirst(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // scrollableCursorFirst

    public oracle.toplink.internal.remote.Transporter scrollableCursorAfterLast(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("scrollableCursorAfterLast", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return scrollableCursorAfterLast(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // scrollableCursorAfterLast

    public oracle.toplink.internal.remote.Transporter cursoredStreamClose(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("cursoredStreamClose", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return cursoredStreamClose(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // cursoredStreamClose

    public oracle.toplink.internal.remote.Transporter getSequenceNumberNamed(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("getSequenceNumberNamed", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return getSequenceNumberNamed(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // getSequenceNumberNamed

    public oracle.toplink.internal.remote.Transporter scrollableCursorClose(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("scrollableCursorClose", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return scrollableCursorClose(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // scrollableCursorClose

    public oracle.toplink.internal.remote.Transporter processCommand(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("processCommand", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return processCommand(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // processCommand

    public oracle.toplink.internal.remote.Transporter cursorSelectObjects(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("cursorSelectObjects", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return cursorSelectObjects(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // cursorSelectObjects

    public oracle.toplink.internal.remote.Transporter scrollableCursorLast(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("scrollableCursorLast", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return scrollableCursorLast(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // scrollableCursorLast

    public oracle.toplink.internal.remote.Transporter executeNamedQuery(oracle.toplink.internal.remote.Transporter arg0, oracle.toplink.internal.remote.Transporter arg1, oracle.toplink.internal.remote.Transporter arg2) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("executeNamedQuery", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg1);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg2);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return executeNamedQuery(arg0, arg1, arg2);
        } finally {
            _releaseReply(_in);
        }
    }
    // executeNamedQuery

    public oracle.toplink.internal.remote.Transporter scrollableCursorBeforeFirst(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("scrollableCursorBeforeFirst", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return scrollableCursorBeforeFirst(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // scrollableCursorBeforeFirst

    public oracle.toplink.internal.remote.Transporter scrollableCursorIsBeforeFirst(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("scrollableCursorIsBeforeFirst", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return scrollableCursorIsBeforeFirst(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // scrollableCursorIsBeforeFirst

    public oracle.toplink.internal.remote.Transporter beginTransaction() {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("beginTransaction", true);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return beginTransaction();
        } finally {
            _releaseReply(_in);
        }
    }
    // beginTransaction

    public oracle.toplink.internal.remote.Transporter initializeIdentityMapsOnServerSession() {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("initializeIdentityMapsOnServerSession", true);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return initializeIdentityMapsOnServerSession();
        } finally {
            _releaseReply(_in);
        }
    }
    // initializeIdentityMapsOnServerSession

    public oracle.toplink.internal.remote.Transporter scrollableCursorIsLast(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("scrollableCursorIsLast", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return scrollableCursorIsLast(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // scrollableCursorIsLast

    public oracle.toplink.internal.remote.Transporter scrollableCursorSize(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("scrollableCursorSize", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return scrollableCursorSize(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // scrollableCursorSize

    public oracle.toplink.internal.remote.Transporter scrollableCursorIsFirst(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("scrollableCursorIsFirst", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return scrollableCursorIsFirst(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // scrollableCursorIsFirst

    public oracle.toplink.internal.remote.Transporter getDescriptor(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("getDescriptor", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return getDescriptor(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // getDescriptor

    public oracle.toplink.internal.remote.Transporter cursoredStreamSize(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("cursoredStreamSize", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return cursoredStreamSize(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // cursoredStreamSize

    public oracle.toplink.internal.remote.Transporter scrollableCursorRelative(oracle.toplink.internal.remote.Transporter arg0, int arg1) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("scrollableCursorRelative", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _out.write_long(arg1);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return scrollableCursorRelative(arg0, arg1);
        } finally {
            _releaseReply(_in);
        }
    }
    // scrollableCursorRelative

    public oracle.toplink.internal.remote.Transporter commitTransaction() {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("commitTransaction", true);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return commitTransaction();
        } finally {
            _releaseReply(_in);
        }
    }
    // commitTransaction

    public oracle.toplink.internal.remote.Transporter rollbackTransaction() {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("rollbackTransaction", true);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return rollbackTransaction();
        } finally {
            _releaseReply(_in);
        }
    }
    // rollbackTransaction

    public oracle.toplink.internal.remote.Transporter instantiateRemoteValueHolderOnServer(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("instantiateRemoteValueHolderOnServer", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return instantiateRemoteValueHolderOnServer(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // instantiateRemoteValueHolderOnServer

    public oracle.toplink.internal.remote.Transporter scrollableCursorNextObject(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("scrollableCursorNextObject", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return scrollableCursorNextObject(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // scrollableCursorNextObject

    public oracle.toplink.internal.remote.Transporter scrollableCursorPreviousObject(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("scrollableCursorPreviousObject", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return scrollableCursorPreviousObject(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // scrollableCursorPreviousObject

    public oracle.toplink.internal.remote.Transporter scrollableCursorIsAfterLast(oracle.toplink.internal.remote.Transporter arg0) {
        org.omg.CORBA.portable.InputStream _in = null;
        try {
            org.omg.CORBA.portable.OutputStream _out = _request("scrollableCursorIsAfterLast", true);
            oracle.toplink.remote.corba.sun.TransporterHelper.write(_out, arg0);
            _in = _invoke(_out);
            oracle.toplink.internal.remote.Transporter __result = oracle.toplink.remote.corba.sun.TransporterHelper.read(_in);
            return __result;
        } catch (org.omg.CORBA.portable.ApplicationException _ex) {
            _in = _ex.getInputStream();
            String _id = _ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException _rm) {
            return scrollableCursorIsAfterLast(arg0);
        } finally {
            _releaseReply(_in);
        }
    }
    // scrollableCursorIsAfterLast

    // Type-specific CORBA::Object operations
    private static String[] __ids = { "IDL:oracle/toplink/remote/corba/sun/CORBARemoteSessionController:1.0" };

    public String[] _ids() {
        return (String[])__ids.clone();
    }

    private void readObject(java.io.ObjectInputStream s) {
        try {
            String str = s.readUTF();
            org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init().string_to_object(str);
            org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate();
            _set_delegate(delegate);
        } catch (java.io.IOException e) {
        }
    }

    private void writeObject(java.io.ObjectOutputStream s) {
        try {
            String str = org.omg.CORBA.ORB.init().object_to_string(this);
            s.writeUTF(str);
        } catch (java.io.IOException e) {
        }
    }
}// class _CORBARemoteSessionControllerStub
