// Copyright (c) 1998, 2006, Oracle. All rights reserved.  
package oracle.toplink.remote.corba.sun;


/**
* INTERNAL:
* oracle/toplink/remote/corba/sun/_CORBARemoteSessionControllerImplBase.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from d:/StarTeam/DIDev/Pine/TopLink/DISource/IDLs/CorbaRemoteSessionControllerSun.idl
* Thursday, May 3, 2001 1:36:59 PM EDT
*/
public abstract class _CORBARemoteSessionControllerImplBase extends org.omg.CORBA.portable.ObjectImpl implements oracle.toplink.remote.corba.sun.CORBARemoteSessionController, org.omg.CORBA.portable.InvokeHandler {
    // Constructors
    public _CORBARemoteSessionControllerImplBase() {
    }

    private static java.util.Hashtable _methods = new java.util.Hashtable();

    static {
        _methods.put("getLogin", new java.lang.Integer(2));
        _methods.put("scrollableCursorCurrentIndex", new java.lang.Integer(5));
        _methods.put("commitRootUnitOfWork", new java.lang.Integer(6));
        _methods.put("scrollableCursorAbsolute", new java.lang.Integer(8));
        _methods.put("cursoredStreamNextPage", new java.lang.Integer(10));
        _methods.put("executeQuery", new java.lang.Integer(14));
        _methods.put("scrollableCursorFirst", new java.lang.Integer(15));
        _methods.put("scrollableCursorAfterLast", new java.lang.Integer(18));
        _methods.put("cursoredStreamClose", new java.lang.Integer(19));
        _methods.put("getSequenceNumberNamed", new java.lang.Integer(22));
        _methods.put("scrollableCursorClose", new java.lang.Integer(24));
        _methods.put("processCommand", new java.lang.Integer(25));
        _methods.put("cursorSelectObjects", new java.lang.Integer(27));
        _methods.put("scrollableCursorLast", new java.lang.Integer(29));
        _methods.put("executeNamedQuery", new java.lang.Integer(31));
        _methods.put("scrollableCursorBeforeFirst", new java.lang.Integer(33));
        _methods.put("scrollableCursorIsBeforeFirst", new java.lang.Integer(34));
        _methods.put("beginTransaction", new java.lang.Integer(35));
        _methods.put("initializeIdentityMapsOnServerSession", new java.lang.Integer(36));
        _methods.put("scrollableCursorIsLast", new java.lang.Integer(37));
        _methods.put("scrollableCursorSize", new java.lang.Integer(38));
        _methods.put("scrollableCursorIsFirst", new java.lang.Integer(39));
        _methods.put("getDescriptor", new java.lang.Integer(40));
        _methods.put("cursoredStreamSize", new java.lang.Integer(41));
        _methods.put("scrollableCursorRelative", new java.lang.Integer(42));
        _methods.put("commitTransaction", new java.lang.Integer(45));
        _methods.put("rollbackTransaction", new java.lang.Integer(47));
        _methods.put("instantiateRemoteValueHolderOnServer", new java.lang.Integer(52));
        _methods.put("scrollableCursorNextObject", new java.lang.Integer(53));
        _methods.put("scrollableCursorIsAfterLast", new java.lang.Integer(54));
        _methods.put("getDefaultReadOnlyClasses", new java.lang.Integer(56));
        _methods.put("scrollableCursorPreviousObject", new java.lang.Integer(57));
    }

    public org.omg.CORBA.portable.OutputStream _invoke(String method, org.omg.CORBA.portable.InputStream in, org.omg.CORBA.portable.ResponseHandler rh) {
        org.omg.CORBA.portable.OutputStream out = null;
        java.lang.Integer __method = (java.lang.Integer)_methods.get(method);
        if (__method == null) {
            throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        switch (__method.intValue()) {
        case 2:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/getLogin
         {
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.getLogin();
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 5:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/scrollableCursorCurrentIndex
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.scrollableCursorCurrentIndex(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 6:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/commitRootUnitOfWork
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.commitRootUnitOfWork(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 8:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/scrollableCursorAbsolute
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            int arg1 = in.read_long();
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.scrollableCursorAbsolute(arg0, arg1);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 10:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/cursoredStreamNextPage
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            int arg1 = in.read_long();
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.cursoredStreamNextPage(arg0, arg1);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 14:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/executeQuery
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.executeQuery(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 15:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/scrollableCursorFirst
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.scrollableCursorFirst(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 18:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/scrollableCursorAfterLast
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.scrollableCursorAfterLast(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 19:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/cursoredStreamClose
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.cursoredStreamClose(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 22:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/getSequenceNumberNamed
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.getSequenceNumberNamed(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 24:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/scrollableCursorClose
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.scrollableCursorClose(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 25:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/processCommand
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.processCommand(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 27:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/cursorSelectObjects
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.cursorSelectObjects(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 29:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/scrollableCursorLast
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.scrollableCursorLast(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 31:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/executeNamedQuery
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter arg1 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter arg2 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.executeNamedQuery(arg0, arg1, arg2);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 33:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/scrollableCursorBeforeFirst
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.scrollableCursorBeforeFirst(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 34:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/scrollableCursorIsBeforeFirst
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.scrollableCursorIsBeforeFirst(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 35:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/beginTransaction
         {
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.beginTransaction();
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 36:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/initializeIdentityMapsOnServerSession
         {
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.initializeIdentityMapsOnServerSession();
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 37:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/scrollableCursorIsLast
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.scrollableCursorIsLast(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 38:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/scrollableCursorSize
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.scrollableCursorSize(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 39:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/scrollableCursorIsFirst
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.scrollableCursorIsFirst(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 40:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/getDescriptor
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.getDescriptor(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 41:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/cursoredStreamSize
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.cursoredStreamSize(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 42:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/scrollableCursorRelative
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            int arg1 = in.read_long();
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.scrollableCursorRelative(arg0, arg1);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 45:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/commitTransaction
         {
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.commitTransaction();
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 47:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/rollbackTransaction
         {
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.rollbackTransaction();
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 52:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/instantiateRemoteValueHolderOnServer
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.instantiateRemoteValueHolderOnServer(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 53:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/scrollableCursorNextObject
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.scrollableCursorNextObject(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 54:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/scrollableCursorIsAfterLast
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.scrollableCursorIsAfterLast(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 56:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/getDefaultReadOnlyClasses
         {
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.getDefaultReadOnlyClasses();
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        case 57:// oracle/toplink/remote/corba/sun/CORBARemoteSessionController/scrollableCursorPreviousObject
         {
            oracle.toplink.internal.remote.Transporter arg0 = oracle.toplink.remote.corba.sun.TransporterHelper.read(in);
            oracle.toplink.internal.remote.Transporter __result = null;
            __result = this.scrollableCursorPreviousObject(arg0);
            out = rh.createReply();
            oracle.toplink.remote.corba.sun.TransporterHelper.write(out, __result);
            break;
        }
        default:
            throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        return out;
    }
    // _invoke

    // Type-specific CORBA::Object operations
    private static String[] __ids = { "IDL:oracle/toplink/remote/corba/sun/CORBARemoteSessionController:1.0" };

    public String[] _ids() {
        return __ids;
    }
}// class _CORBARemoteSessionControllerImplBase
