// Copyright (c) 1998, 2006, Oracle. All rights reserved.  
package oracle.toplink.remote.corba.sun;


/**
 * INTERNAL:
* oracle/toplink/remote/corba/sun/CORBARemoteSessionController.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaRemoteSessionControllerSun.idl
* Monday, November 19, 2001 1:51:44 o'clock PM EST
*/
public interface CORBARemoteSessionController extends CORBARemoteSessionControllerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
}// interface CORBARemoteSessionController
