// Copyright (c) 1998, 2006, Oracle. All rights reserved.  
package oracle.toplink.remote.corba.sun;


/**
 * INTERNAL:
* oracle/toplink/remote/corba/sun/CORBARemoteSessionControllerHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaRemoteSessionControllerSun.idl
* Monday, November 19, 2001 1:51:44 o'clock PM EST
*/
public final class CORBARemoteSessionControllerHolder implements org.omg.CORBA.portable.Streamable {
    public oracle.toplink.remote.corba.sun.CORBARemoteSessionController value = null;

    public CORBARemoteSessionControllerHolder() {
    }

    public CORBARemoteSessionControllerHolder(oracle.toplink.remote.corba.sun.CORBARemoteSessionController initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = oracle.toplink.remote.corba.sun.CORBARemoteSessionControllerHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        oracle.toplink.remote.corba.sun.CORBARemoteSessionControllerHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return oracle.toplink.remote.corba.sun.CORBARemoteSessionControllerHelper.type();
    }
}