// Copyright (c) 1998, 2006, Oracle. All rights reserved.  
package oracle.toplink.remote.corba.sun;


/**
 * INTERNAL:
* oracle/toplink/remote/corba/sun/CORBARemoteSessionControllerOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaRemoteSessionControllerSun.idl
* Monday, November 19, 2001 1:51:44 o'clock PM EST
*/
public interface CORBARemoteSessionControllerOperations {
    oracle.toplink.internal.remote.Transporter getLogin();

    oracle.toplink.internal.remote.Transporter getDefaultReadOnlyClasses();

    oracle.toplink.internal.remote.Transporter scrollableCursorCurrentIndex(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter commitRootUnitOfWork(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter scrollableCursorAbsolute(oracle.toplink.internal.remote.Transporter arg0, int arg1);

    oracle.toplink.internal.remote.Transporter cursoredStreamNextPage(oracle.toplink.internal.remote.Transporter arg0, int arg1);

    oracle.toplink.internal.remote.Transporter executeQuery(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter scrollableCursorFirst(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter scrollableCursorAfterLast(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter cursoredStreamClose(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter getSequenceNumberNamed(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter scrollableCursorClose(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter processCommand(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter cursorSelectObjects(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter scrollableCursorLast(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter executeNamedQuery(oracle.toplink.internal.remote.Transporter arg0, oracle.toplink.internal.remote.Transporter arg1, oracle.toplink.internal.remote.Transporter arg2);

    oracle.toplink.internal.remote.Transporter scrollableCursorBeforeFirst(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter scrollableCursorIsBeforeFirst(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter beginTransaction();

    oracle.toplink.internal.remote.Transporter initializeIdentityMapsOnServerSession();

    oracle.toplink.internal.remote.Transporter scrollableCursorIsLast(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter scrollableCursorSize(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter scrollableCursorIsFirst(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter getDescriptor(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter cursoredStreamSize(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter scrollableCursorRelative(oracle.toplink.internal.remote.Transporter arg0, int arg1);

    oracle.toplink.internal.remote.Transporter commitTransaction();

    oracle.toplink.internal.remote.Transporter rollbackTransaction();

    oracle.toplink.internal.remote.Transporter instantiateRemoteValueHolderOnServer(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter scrollableCursorNextObject(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter scrollableCursorPreviousObject(oracle.toplink.internal.remote.Transporter arg0);

    oracle.toplink.internal.remote.Transporter scrollableCursorIsAfterLast(oracle.toplink.internal.remote.Transporter arg0);
}// interface CORBARemoteSessionControllerOperations
