// Copyright (c) 1998, 2006, Oracle. All rights reserved.  
// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.
package oracle.toplink.remote.rmi;

public final class RMIRemoteSessionControllerDispatcher_Stub extends java.rmi.server.RemoteStub implements oracle.toplink.remote.rmi.RMIRemoteSessionController, java.rmi.Remote {
    private static final long serialVersionUID = 2;
    private static java.lang.reflect.Method $method_beginTransaction_0;
    private static java.lang.reflect.Method $method_commitRootUnitOfWork_1;
    private static java.lang.reflect.Method $method_commitTransaction_2;
    private static java.lang.reflect.Method $method_cursorSelectObjects_7;
    private static java.lang.reflect.Method $method_cursoredStreamClose_8;
    private static java.lang.reflect.Method $method_cursoredStreamNextPage_9;
    private static java.lang.reflect.Method $method_cursoredStreamSize_10;
    private static java.lang.reflect.Method $method_executeNamedQuery_11;
    private static java.lang.reflect.Method $method_executeQuery_12;
    private static java.lang.reflect.Method $method_getDefaultReadOnlyClasses_13;
    private static java.lang.reflect.Method $method_getDescriptor_14;
    private static java.lang.reflect.Method $method_getLogin_18;
    private static java.lang.reflect.Method $method_getSequenceNumberNamed_21;
    private static java.lang.reflect.Method $method_initializeIdentityMapsOnServerSession_24;
    private static java.lang.reflect.Method $method_instantiateRemoteValueHolderOnServer_25;
    private static java.lang.reflect.Method $method_processCommand_31;
    private static java.lang.reflect.Method $method_rollbackTransaction_34;
    private static java.lang.reflect.Method $method_scrollableCursorAbsolute_35;
    private static java.lang.reflect.Method $method_scrollableCursorAfterLast_36;
    private static java.lang.reflect.Method $method_scrollableCursorBeforeFirst_37;
    private static java.lang.reflect.Method $method_scrollableCursorClose_38;
    private static java.lang.reflect.Method $method_scrollableCursorCurrentIndex_39;
    private static java.lang.reflect.Method $method_scrollableCursorFirst_40;
    private static java.lang.reflect.Method $method_scrollableCursorIsAfterLast_41;
    private static java.lang.reflect.Method $method_scrollableCursorIsBeforeFirst_42;
    private static java.lang.reflect.Method $method_scrollableCursorIsFirst_43;
    private static java.lang.reflect.Method $method_scrollableCursorIsLast_44;
    private static java.lang.reflect.Method $method_scrollableCursorLast_45;
    private static java.lang.reflect.Method $method_scrollableCursorNextObject_46;
    private static java.lang.reflect.Method $method_scrollableCursorPreviousObject_47;
    private static java.lang.reflect.Method $method_scrollableCursorRelative_48;
    private static java.lang.reflect.Method $method_scrollableCursorSize_49;

    static {
        try {
            $method_beginTransaction_0 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("beginTransaction", new java.lang.Class[] {  });
            $method_commitRootUnitOfWork_1 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("commitRootUnitOfWork", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_commitTransaction_2 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("commitTransaction", new java.lang.Class[] {  });
            $method_cursorSelectObjects_7 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("cursorSelectObjects", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_cursoredStreamClose_8 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("cursoredStreamClose", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_cursoredStreamNextPage_9 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("cursoredStreamNextPage", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class, int.class });
            $method_cursoredStreamSize_10 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("cursoredStreamSize", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_executeNamedQuery_11 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("executeNamedQuery", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class, oracle.toplink.internal.remote.Transporter.class, oracle.toplink.internal.remote.Transporter.class });
            $method_executeQuery_12 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("executeQuery", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_getDefaultReadOnlyClasses_13 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("getDefaultReadOnlyClasses", new java.lang.Class[] {  });
            $method_getDescriptor_14 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("getDescriptor", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_getLogin_18 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("getLogin", new java.lang.Class[] {  });
            $method_getSequenceNumberNamed_21 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("getSequenceNumberNamed", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_initializeIdentityMapsOnServerSession_24 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("initializeIdentityMapsOnServerSession", new java.lang.Class[] {  });
            $method_instantiateRemoteValueHolderOnServer_25 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("instantiateRemoteValueHolderOnServer", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_processCommand_31 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("processCommand", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_rollbackTransaction_34 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("rollbackTransaction", new java.lang.Class[] {  });
            $method_scrollableCursorAbsolute_35 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("scrollableCursorAbsolute", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class, int.class });
            $method_scrollableCursorAfterLast_36 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("scrollableCursorAfterLast", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_scrollableCursorBeforeFirst_37 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("scrollableCursorBeforeFirst", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_scrollableCursorClose_38 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("scrollableCursorClose", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_scrollableCursorCurrentIndex_39 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("scrollableCursorCurrentIndex", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_scrollableCursorFirst_40 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("scrollableCursorFirst", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_scrollableCursorIsAfterLast_41 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("scrollableCursorIsAfterLast", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_scrollableCursorIsBeforeFirst_42 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("scrollableCursorIsBeforeFirst", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_scrollableCursorIsFirst_43 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("scrollableCursorIsFirst", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_scrollableCursorIsLast_44 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("scrollableCursorIsLast", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_scrollableCursorLast_45 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("scrollableCursorLast", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_scrollableCursorNextObject_46 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("scrollableCursorNextObject", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_scrollableCursorPreviousObject_47 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("scrollableCursorPreviousObject", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
            $method_scrollableCursorRelative_48 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("scrollableCursorRelative", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class, int.class });
            $method_scrollableCursorSize_49 = oracle.toplink.remote.rmi.RMIRemoteSessionController.class.getMethod("scrollableCursorSize", new java.lang.Class[] { oracle.toplink.internal.remote.Transporter.class });
        } catch (java.lang.NoSuchMethodException e) {
            throw new java.lang.NoSuchMethodError("stub class initialization failed");
        }
    }

    // constructors
    public RMIRemoteSessionControllerDispatcher_Stub(java.rmi.server.RemoteRef ref) {
        super(ref);
    }

    // methods from remote interfaces
    // implementation of beginTransaction()
    public oracle.toplink.internal.remote.Transporter beginTransaction() throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_beginTransaction_0, null, -1564030960788921896L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of commitRootUnitOfWork(Transporter)
    public oracle.toplink.internal.remote.Transporter commitRootUnitOfWork(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_commitRootUnitOfWork_1, new java.lang.Object[] { $param_Transporter_1 }, -6764127992203581314L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of commitTransaction()
    public oracle.toplink.internal.remote.Transporter commitTransaction() throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_commitTransaction_2, null, 4977078307842394526L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of cursorSelectObjects(Transporter)
    public oracle.toplink.internal.remote.Transporter cursorSelectObjects(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_cursorSelectObjects_7, new java.lang.Object[] { $param_Transporter_1 }, 8788443825781269658L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of cursoredStreamClose(Transporter)
    public oracle.toplink.internal.remote.Transporter cursoredStreamClose(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_cursoredStreamClose_8, new java.lang.Object[] { $param_Transporter_1 }, 976036008371679883L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of cursoredStreamNextPage(Transporter, int)
    public oracle.toplink.internal.remote.Transporter cursoredStreamNextPage(oracle.toplink.internal.remote.Transporter $param_Transporter_1, int $param_int_2) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_cursoredStreamNextPage_9, new java.lang.Object[] { $param_Transporter_1, new java.lang.Integer($param_int_2) }, 4199265800908905841L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of cursoredStreamSize(Transporter)
    public oracle.toplink.internal.remote.Transporter cursoredStreamSize(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_cursoredStreamSize_10, new java.lang.Object[] { $param_Transporter_1 }, -1811156713203555615L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of executeNamedQuery(Transporter, Transporter, Transporter)
    public oracle.toplink.internal.remote.Transporter executeNamedQuery(oracle.toplink.internal.remote.Transporter $param_Transporter_1, oracle.toplink.internal.remote.Transporter $param_Transporter_2, oracle.toplink.internal.remote.Transporter $param_Transporter_3) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_executeNamedQuery_11, new java.lang.Object[] { $param_Transporter_1, $param_Transporter_2, $param_Transporter_3 }, 4296218800612624371L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of executeQuery(Transporter)
    public oracle.toplink.internal.remote.Transporter executeQuery(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_executeQuery_12, new java.lang.Object[] { $param_Transporter_1 }, 645188094302932640L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of getDefaultReadOnlyClasses()
    public oracle.toplink.internal.remote.Transporter getDefaultReadOnlyClasses() throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_getDefaultReadOnlyClasses_13, null, 2190672741523431440L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of getDescriptor(Transporter)
    public oracle.toplink.internal.remote.Transporter getDescriptor(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_getDescriptor_14, new java.lang.Object[] { $param_Transporter_1 }, -7985165378324364447L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of getLogin()
    public oracle.toplink.internal.remote.Transporter getLogin() throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_getLogin_18, null, 9079116349899427721L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of getSequenceNumberNamed(Transporter)
    public oracle.toplink.internal.remote.Transporter getSequenceNumberNamed(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_getSequenceNumberNamed_21, new java.lang.Object[] { $param_Transporter_1 }, 8087106181665380408L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of initializeIdentityMapsOnServerSession()
    public oracle.toplink.internal.remote.Transporter initializeIdentityMapsOnServerSession() throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_initializeIdentityMapsOnServerSession_24, null, -3777386908731746180L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of instantiateRemoteValueHolderOnServer(Transporter)
    public oracle.toplink.internal.remote.Transporter instantiateRemoteValueHolderOnServer(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_instantiateRemoteValueHolderOnServer_25, new java.lang.Object[] { $param_Transporter_1 }, 540076699958921253L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of processCommand(Transporter)
    public oracle.toplink.internal.remote.Transporter processCommand(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_processCommand_31, new java.lang.Object[] { $param_Transporter_1 }, -6148568353133330357L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of rollbackTransaction()
    public oracle.toplink.internal.remote.Transporter rollbackTransaction() throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_rollbackTransaction_34, null, 9093840039375228752L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of scrollableCursorAbsolute(Transporter, int)
    public oracle.toplink.internal.remote.Transporter scrollableCursorAbsolute(oracle.toplink.internal.remote.Transporter $param_Transporter_1, int $param_int_2) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_scrollableCursorAbsolute_35, new java.lang.Object[] { $param_Transporter_1, new java.lang.Integer($param_int_2) }, -935536649247306863L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of scrollableCursorAfterLast(Transporter)
    public oracle.toplink.internal.remote.Transporter scrollableCursorAfterLast(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_scrollableCursorAfterLast_36, new java.lang.Object[] { $param_Transporter_1 }, 3952302446825647348L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of scrollableCursorBeforeFirst(Transporter)
    public oracle.toplink.internal.remote.Transporter scrollableCursorBeforeFirst(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_scrollableCursorBeforeFirst_37, new java.lang.Object[] { $param_Transporter_1 }, -317831215902806017L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of scrollableCursorClose(Transporter)
    public oracle.toplink.internal.remote.Transporter scrollableCursorClose(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_scrollableCursorClose_38, new java.lang.Object[] { $param_Transporter_1 }, -8200717090697427872L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of scrollableCursorCurrentIndex(Transporter)
    public oracle.toplink.internal.remote.Transporter scrollableCursorCurrentIndex(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_scrollableCursorCurrentIndex_39, new java.lang.Object[] { $param_Transporter_1 }, 7304614908603244674L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of scrollableCursorFirst(Transporter)
    public oracle.toplink.internal.remote.Transporter scrollableCursorFirst(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_scrollableCursorFirst_40, new java.lang.Object[] { $param_Transporter_1 }, 5878637031946465728L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of scrollableCursorIsAfterLast(Transporter)
    public oracle.toplink.internal.remote.Transporter scrollableCursorIsAfterLast(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_scrollableCursorIsAfterLast_41, new java.lang.Object[] { $param_Transporter_1 }, 1950493428357985873L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of scrollableCursorIsBeforeFirst(Transporter)
    public oracle.toplink.internal.remote.Transporter scrollableCursorIsBeforeFirst(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_scrollableCursorIsBeforeFirst_42, new java.lang.Object[] { $param_Transporter_1 }, -4475509331546789229L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of scrollableCursorIsFirst(Transporter)
    public oracle.toplink.internal.remote.Transporter scrollableCursorIsFirst(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_scrollableCursorIsFirst_43, new java.lang.Object[] { $param_Transporter_1 }, -4351521036354378427L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of scrollableCursorIsLast(Transporter)
    public oracle.toplink.internal.remote.Transporter scrollableCursorIsLast(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_scrollableCursorIsLast_44, new java.lang.Object[] { $param_Transporter_1 }, 6420185257438460190L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of scrollableCursorLast(Transporter)
    public oracle.toplink.internal.remote.Transporter scrollableCursorLast(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_scrollableCursorLast_45, new java.lang.Object[] { $param_Transporter_1 }, -966605088298494983L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of scrollableCursorNextObject(Transporter)
    public oracle.toplink.internal.remote.Transporter scrollableCursorNextObject(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_scrollableCursorNextObject_46, new java.lang.Object[] { $param_Transporter_1 }, -4453853847252595406L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of scrollableCursorPreviousObject(Transporter)
    public oracle.toplink.internal.remote.Transporter scrollableCursorPreviousObject(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_scrollableCursorPreviousObject_47, new java.lang.Object[] { $param_Transporter_1 }, 3335393418546065504L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of scrollableCursorRelative(Transporter, int)
    public oracle.toplink.internal.remote.Transporter scrollableCursorRelative(oracle.toplink.internal.remote.Transporter $param_Transporter_1, int $param_int_2) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_scrollableCursorRelative_48, new java.lang.Object[] { $param_Transporter_1, new java.lang.Integer($param_int_2) }, -3288472928931975286L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of scrollableCursorSize(Transporter)
    public oracle.toplink.internal.remote.Transporter scrollableCursorSize(oracle.toplink.internal.remote.Transporter $param_Transporter_1) throws java.rmi.RemoteException {
        try {
            Object $result = ref.invoke(this, $method_scrollableCursorSize_49, new java.lang.Object[] { $param_Transporter_1 }, 279840170576960627L);
            return ((oracle.toplink.internal.remote.Transporter)$result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }
}